### ISSUE TITLE
Not work orm:convert-mapping

### ISSUE THREAD

**Issue by thrass** [daycry/doctrine#1]
Hi,

I try run this command:

> vendor/bin/doctrine orm:convert-mapping --namespace='App\Models\Entity' --force --from-database annotation .

This show "Processing entity 'App\Models\Entity\Banner'" but when run the next command

> vendor/bin/doctrine orm:generate-entities .

Not created the file in "App\Models\Entity\Banner" and show this warning

> [WARNING] Command orm:generate-entities is deprecated and will be removed in Doctrine ORM 3.0.

What I do to fix this? Delete the folder Entity and excecute all command again?

My system:
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:43) ( NTS )
Composer version 2.0.8 2020-12-03 17:20:38
Ubuntu 18.04.5 LTS

**Comment by daycry** [comment]
It is a warning message that in version 3 of doctrine, that command will
disappear, but I am using version 2.

The command should work the same, send me screenshots to try to see what
happens.

Thanks

**Comment by thrass** [comment]
![report bug dpctrine](https://user-images.githubusercontent.com/13186528/103226901-83ce5880-4903-11eb-864e-bb863b89dca1.png)

If you're planned migrate to Doctrine 3?

**Comment by daycry** [comment]
I have planned to migrate the version, but it has only been released for 1
month, I am waiting for it to mature a bit.

Thanks.

**Comment by daycry** [comment]
It is an obsolete function notice in doctrine 3
