### ISSUE TITLE
Oracle OCI8 configuration support in convertDbConfig method

### ISSUE THREAD

**Issue by bert126** [daycry/doctrine#11]
Would it be possible to add the standard **"SERVICENAME"** Oracle connection option to the existing **convertDbConfig** method?
This would make your library fully compatible with CodeIgniter 4 and OCI8 natively.

```
public function convertDbConfig($db)
    {
        $connectionOptions = [];
        if ($db->DBDriver === 'pdo') {
            return $this->convertDbConfigPdo($db);
        } else {
            $connectionOptions = [
                'driver'   => strtolower($db->DBDriver),
                'user'     => $db->username,
                'password' => $db->password,
                'host'     => $db->hostname,
                'dbname'   => $db->database,
                'charset'  => $db->charset,
                'port'     => $db->port,
                'servicename'     => $db->servicename
            ];
        }
        return $connectionOptions;
    }

```

**Comment by daycry** [comment]
Hi,

Codeigniter 4 has a native connection with oci8, but let me see this
feature.

Thank you!

**Comment by bert126** [comment]
> Hi, Codeigniter 4 has a native connection with oci8, but let me see this feature. Thank you!
> […](#)

Yes, CI4 supports OCI8 driver since v4.2+, but we still have to manually modify your Doctrine.php to add the SERVICENAME parameter to it so far. 

The servicename is a standard parameter to connect to Oracle databases and is therefore implemented in the [Doctrine DBAL configuration](https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/configuration.html#pdo-oci-oci8).

About the native PDO_OCI, Oracle and Doctrine both continue to recommend the OCI8 driver instead of PDO_OCI (clob issues) and it seems Oracle does not contribute anymore to PDO_OCI.

Thank you in advance!

**Comment by daycry** [comment]
Okis, I will do this changes

**Comment by daycry** [comment]
- Solved

**Comment by bert126** [comment]
I have asked CI to adapt their OCI8 driver accordingly since it seems they also miss the SERVICENAME property.
Currently the workaround is to use the DBNAME property instead.
