### ISSUE TITLE
Entity class not found exception

### ISSUE THREAD

**Issue by Rajamalli** [daycry/doctrine#12]
My error:

`Doctrine\Persistence\Mapping\MappingException`
`Class Entities\UserDataTest does not exist`

I changed the Entity folder name in /vendor/daycry/doctrine/src/Config/Doctrine.php:
`public $folderEntity = APPPATH . 'Models/Entities';`
`public $folderMapping = APPPATH . 'Models/Mappings';`

i also used yaml driver and made changes in /vendor/daycry/doctrine/src/Doctrine.php:

` //$reader = new AnnotationReader();`
`$driver = new \Doctrine\ORM\Mapping\Driver\YamlDriver(array( $configuration->folderMapping ));`

Code that gives this error :
`$data = $this->doctrine->em->getRepository('Entities\UserDataTest')->findOneBy( array('id' => 1 ));`

**Comment by daycry** [comment]
Try this:

App\Models\Entities\UserDataTest.

This example is in readme.md file

**Comment by Rajamalli** [comment]
Got this error:

`Doctrine\Persistence\Mapping\MappingException`
`Class 'App\Models\Entities\UserDataTest' does not exist`


What are the files to be configured for including entities and mappings folder?

**Comment by daycry** [comment]
If you follow all the steps in the documentation, without changes you can
run it.
The default configuration in Doctrine.php config file is well.

**Comment by bert126** [comment]
> Got this error:
> 
> `Doctrine\Persistence\Mapping\MappingException` `Class 'App\Models\Entities\UserDataTest' does not exist`
> 
> What are the files to be configured for including entities and mappings folder?

For me, this is not a daycry/doctrine issue but a generic autoload question.

Try to add this to your composer.json

```
"autoload": {
        "psr-4": {
            "": ["app/Models/Entities","app/Models/Repositories"]
        },
    },
```

and your Entities will be available from everywhere.
