### ISSUE TITLE
Errors while running cli-config.php under codeigniter 4.5.1

### ISSUE THREAD

**Issue by foxbille** [daycry/doctrine#13]
Hello,
Got errors when running cli-config under ci4.5.1 :
This "system/bootstrap.php" is no longer used. If you are seeing this error message,
the upgrade is not complete. Please refer to the upgrade guide and complete the upgrade.
See https://codeigniter4.github.io/userguide/installation/upgrade_450.html

PHP Fatal error:  Uncaught Error: Undefined constant "CodeIgniter\Log\CI_DEBUG" in [..]/daycry/vendor/codeigniter4/framework/system/Log/Logger.php:124
have I done something wrong?
Eric

**Comment by daycry** [comment]
Hi

Try v4.1.1 and run copy cli-config.php in your project
