### ISSUE TITLE
BC BREAK: Removed EchoSQLLogger

### ISSUE THREAD

**Issue by agung-wete** [daycry/doctrine#9]
see https://github.com/doctrine/dbal/blob/3.3.x/UPGRADE.md#bc-break-removed-echosqllogger

currently, with this package composer, doctrine\dbal installed version is 3.3.5.
If [DEBUG](https://github.com/daycry/doctrine/blob/b6d7a9957736548a3536a3225363f98aaf9c4f29/src/Config/Doctrine.php#L9) enabled, got error :
```
Class "Doctrine\DBAL\Logging\EchoSQLLogger" not found 
```
We need to update code which has BC BREAK. It would be nice if we also update the DEPRECATED too.

**Comment by daycry** [comment]
I have been reviewing what you tell me and I have commented that part of
code, since right now it is impossible for me to review it since I don't
have time and I can't find reliable information to implement what you say
\Doctrine\DBAL\Logging\Middleware

**Comment by daycry** [comment]
If you want to help me, feel free.
I would appreciate.

**Comment by agung-wete** [comment]
i'll try it.
Also it would be good if we add doctrine debug info to CI debug toolbar: https://codeigniter4.github.io/userguide/testing/debugging.html?highlight=debug#creating-custom-collectors

**Comment by agung-wete** [comment]
which one do you choose ?
- Doctrine\DBAL\Logging\SQLLogger (still deprecated)
- \Doctrine\DBAL\Logging\Middleware

**Comment by daycry** [comment]
I think middleware, but doctrine toolbar debug is better and clean.

**Comment by daycry** [comment]
I Will try todo.

Thanks
